version: '3'

services:
  app:
    build: .
    platform: linux/amd64 # For M1 to install google-chrome-stable; However still crashes on M1 when launching chrome (selenium.common.exceptions.WebDriverException: Message: unknown error: unable to discover open window in chrome (Session info: headless chrome=109.0.5414.119))
    command: python flathunt.py
    restart: always
    environment:
      - FLATHUNTER_TARGET_URLS=${FLATHUNTER_TARGET_URLS}
      - FLATHUNTER_DATABASE_LOCATION=${FLATHUNTER_DATABASE_LOCATION}
      - FLATHUNTER_GOOGLE_CLOUD_PROJECT_ID=${FLATHUNTER_GOOGLE_CLOUD_PROJECT_ID}
      - FLATHUNTER_VERBOSE_LOG=${FLATHUNTER_VERBOSE_LOG}
      - FLATHUNTER_LOOP_PERIOD_SECONDS=${FLATHUNTER_LOOP_PERIOD_SECONDS}
      - FLATHUNTER_MESSAGE_FORMAT=${FLATHUNTER_MESSAGE_FORMAT}
      - FLATHUNTER_NOTIFIERS=${FLATHUNTER_NOTIFIERS}
      - FLATHUNTER_TELEGRAM_BOT_TOKEN=${FLATHUNTER_TELEGRAM_BOT_TOKEN}
      - FLATHUNTER_TELEGRAM_RECEIVER_IDS=${FLATHUNTER_TELEGRAM_RECEIVER_IDS}
      - FLATHUNTER_MATTERMOST_WEBHOOK_URL=${FLATHUNTER_MATTERMOST_WEBHOOK_URL}
      - FLATHUNTER_SLACK_WEBHOOK_URL=${FLATHUNTER_SLACK_WEBHOOK_URL}
      - FLATHUNTER_WEBSITE_SESSION_KEY=${FLATHUNTER_WEBSITE_SESSION_KEY}
      - FLATHUNTER_WEBSITE_DOMAIN=${FLATHUNTER_WEBSITE_DOMAIN}
      - FLATHUNTER_2CAPTCHA_KEY=${FLATHUNTER_2CAPTCHA_KEY}
      - FLATHUNTER_IMAGETYPERZ_TOKEN=${FLATHUNTER_IMAGETYPERZ_TOKEN}
      - FLATHUNTER_HEADLESS_BROWSER=yes
    volumes:
      - ./:/usr/src/app # not ideal, but the only way to incorporate the database (processed_ids.db), which is currently created at runtime
